export const cards = [
  {
    date: "20/05/2025",
    title: "عنـوان رئيـسـي",
    desc: "الـعنــوان الـفرعــي هنــا أو التـفــاصـيــل",
  },
  {
    date: "20/05/2025",
    title: "عنـوان رئيـسـي",
    desc: "الـعنــوان الـفرعــي هنــا أو التـفــاصـيــل",
  },
  {
    date: "20/05/2025",
    title: "عنـوان رئيـسـي",
    desc: "الـعنــوان الـفرعــي هنــا أو التـفــاصـيــل",
  },
  {
    date: "20/05/2025",
    title: "عنـوان رئيـسـي",
    desc: "الـعنــوان الـفرعــي هنــا أو التـفــاصـيــل",
  },
];

export const RaceCalendarData = [
  {
    dayNumber: 1,
    dayName: "الخميس",
    events: [
      {
        id: 123,
        name: "سباق السرعة",
        category: "سباق سريع",
        date: "20 مايو 2025",
        time: "03:00 PM - 05:00 PM",
        distenation: 5,
        type: "ترابي",
        age: 4,
        prize: 50000,
      },
      {
        id: 1234,
        name: "سباق السرعة",
        category: "سباق سريع",
        date: "20 مايو 2025",
        time: "03:00 PM - 05:00 PM",
        distenation: 5,
        type: "ترابي",
        age: 4,
        prize: 50000,
      },
      {
        id: 1235,
        name: "سباق السرعة",
        category: "سباق سريع",
        date: "20 مايو 2025",
        time: "03:00 PM - 05:00 PM",
        distenation: 5,
        type: "ترابي",
        age: 4,
        prize: 50000,
      },
    ],
  },
  {
    dayNumber: 2,
    dayName: "الجمعة",
    events: [
      {
        id: 1236,
        name: "سباق السرعة",
        category: "سباق سريع",
        date: "20 مايو 2025",
        time: "03:00 PM - 05:00 PM",
        distenation: 5,
        type: "ترابي",
        age: 4,
        prize: 50000,
      },
    ],
  },
  {
    dayNumber: 5,
    dayName: "الاثنين",
    events: [
      {
        id: 1213,
        name: "سباق السرعة",
        category: "سباق سريع",
        date: "20 مايو 2025",
        time: "03:00 PM - 05:00 PM",
        distenation: 5,
        type: "ترابي",
        age: 4,
        prize: 50000,
      },
      {
        id: 12223,
        name: "سباق السرعة",
        category: "سباق سريع",
        date: "20 مايو 2025",
        time: "03:00 PM - 05:00 PM",
        distenation: 5,
        type: "ترابي",
        age: 4,
        prize: 50000,
      },
      {
        id: 111123,
        name: "سباق السرعة",
        category: "سباق سريع",
        date: "20 مايو 2025",
        time: "03:00 PM - 05:00 PM",
        distenation: 5,
        type: "ترابي",
        age: 4,
        prize: 50000,
      },
    ],
  },
  {
    dayNumber: 7,
    dayName: "الأربعاء",
    events: [
      {
        id: 1231111,
        name: "سباق السرعة",
        category: "سباق سريع",
        date: "20 مايو 2025",
        time: "03:00 PM - 05:00 PM",
        distenation: 5,
        type: "ترابي",
        age: 4,
        prize: 50000,
      },
    ],
  },
  {
    dayNumber: 9,
    dayName: "الجمعة",
    events: [
      {
        id: 1523,
        name: "سباق السرعة",
        category: "سباق سريع",
        date: "20 مايو 2025",
        time: "03:00 PM - 05:00 PM",
        distenation: 5,
        type: "ترابي",
        age: 4,
        prize: 50000,
      },
      {
        id: 153323,
        name: "سباق السرعة",
        category: "سباق سريع",
        date: "20 مايو 2025",
        time: "03:00 PM - 05:00 PM",
        distenation: 5,
        type: "ترابي",
        age: 4,
        prize: 50000,
      },
    ],
  },
  {
    dayNumber: 21,
    dayName: "الأربعاء",
    events: [
      {
        id: 12232352,
        name: "السباق الرئيسي",
        category: "التصنيف الأول",
        date: "21 مايو 2025",
        time: "07:30 PM - 09:30 PM",
        distenation: 7,
        type: "رملي",
        age: 5,
        prize: 150000,
      },
      {
        id: 1243222352,
        name: "سباق السرعة",
        category: "سباق سريع",
        date: "20 مايو 2025",
        time: "03:00 PM - 05:00 PM",
        distenation: 5,
        type: "ترابي",
        age: 4,
        prize: 50000,
      },
    ],
  },
  {
    dayNumber: 22,
    dayName: "الخميس",
    events: [],
  },
  {
    dayNumber: 23,
    dayName: "الجمعة",
    events: [
      {
        id: 144423,

        name: "سباق الناشئين",
        category: "تصنيف الشباب",
        date: "23 مايو 2025",
        time: "05:00 PM - 06:30 PM",
        distenation: 4,
        type: "رملي",
        age: 3,
        prize: 30000,
      },
    ],
  },
  {
    dayNumber: 24,
    dayName: "السبت",
    events: [],
  },
];
